// Generated by Selenium IDE
package exercise;


import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.*;
import java.util.*;

//import java.net.MalformedURLException;
//import java.net.URL;
public class LoginLogoutDemoTest {
	private WebDriver driver;
	@SuppressWarnings("unused")
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@SuppressWarnings("deprecation")
	@Test
	public void loginLogoutDemo() throws InterruptedException {
		driver.get("https://admin-demo.nopcommerce.com/login?ReturnUrl=%2Fadmin%2F");
		driver.manage().window().setSize(new Dimension(1512, 861));
		assertThat(driver.getTitle(), is("Your store. Login"));
		System.out.println(driver.getTitle());
		Thread.sleep(3000);
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".button-1"));
			assert (elements.size() > 0);
		}
		driver.findElement(By.cssSelector(".button-1")).click();
		assertThat(driver.getTitle(), is("Dashboard / nopCommerce administration"));
		System.out.println(driver.getTitle());
		assertThat(driver.findElement(By.cssSelector(".content-header>h1")).getText(), is("Dashboard"));
		driver.findElement(By.linkText("Logout")).click();
		System.out.println("Logout is successful");
	}
}
